# Generated by Django 4.2.1 on 2024-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='addedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
