# Generated by Django 4.2.1 on 2024-03-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0002_member_addeddate_member_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
